apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: robotshop-dev
  name: robot-shop
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8080
